import React from "react"

// create a function that takes in the results of random dice roll and returns a log of the results of all previous rolls next to it
// input: numbers generated by dice rolling component
// output: a running list of all the numbers input
// process: props to send data from dice roller component to counter component, .push to add new data to array of numbers, state to not permanently alter code in browser

const Counter = (props) => {
    return (
    <div className="counterbox">
        <h3>Past Results: </h3>
           <p> {props.results} </p>
    </div>
    )
}

export default Counter